global:
  scrape_interval: 15s

scrape_configs:
  # Scrape host system metrics
  - job_name: 'host_system'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Docker container metrics via cAdvisor
  - job_name: 'docker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['docker_host_ip:8080']
